_target_: src.models.systems.MLPVideoSystem

validation_output_dir: ${hydra:runtime.output_dir}/output


net:
  _target_: src.models.networks.Siren
  in_features: 3
  out_features: 3
  hidden_features: 256
  num_hidden_layers: 4

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00005

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${trainer.max_steps}
  eta_min: ${mul:${model.optimizer.lr}, 0.1}

